// <auto-generated />
using System;
using EfcDataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfcDataAccess.Migrations
{
    [DbContext(typeof(MovieReviewEngineContext))]
    [Migration("20250704142829_MoreContentData")]
    partial class MoreContentData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Domain.Models.Cast", b =>
                {
                    b.Property<Guid>("CastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CastId");

                    b.ToTable("Casts");
                });

            modelBuilder.Entity("Domain.Models.Content", b =>
                {
                    b.Property<Guid>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContentId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            ContentId = new Guid("16fc9521-cd19-40c9-8e06-c9f22ea3f278"),
                            Description = "A sci-fi drama exploring survival and identity.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image3.jpeg",
                            ReleaseDate = new DateTime(2019, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last Horizon",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("e77c2d86-0bea-41ca-93bb-db9cbfe8d014"),
                            Description = "An espionage thriller set during a solar event.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image4.jpeg",
                            ReleaseDate = new DateTime(2019, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Crimson Eclipse",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("7decd574-5d0e-4509-8c30-54394a6f3b02"),
                            Description = "A mystery thriller unraveling secrets in a remote village.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image5.jpeg",
                            ReleaseDate = new DateTime(2020, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Silent River",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("66c85e8b-f354-40dd-ba43-28586a479dcc"),
                            Description = "A detective story with noir aesthetics.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image6.jpeg",
                            ReleaseDate = new DateTime(2021, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Velvet Crimes",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("03cf1925-4bd4-4d08-ab57-988c7c1b862d"),
                            Description = "A survival adventure across the Arctic Circle.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image7.jpeg",
                            ReleaseDate = new DateTime(2018, 9, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Broken Compass",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("4cbf596b-087a-4012-b7f2-fe7528ef6547"),
                            Description = "A cyberpunk action film set in a glowing megacity.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image8.jpeg",
                            ReleaseDate = new DateTime(2020, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Neon Depths",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("72b560c2-f902-4758-9135-7ef3361f231e"),
                            Description = "A romantic drama through time and memory.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image9.jpeg",
                            ReleaseDate = new DateTime(2017, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Letters to a Ghost",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("9820f95d-0a55-4aca-af98-613c1ef41a94"),
                            Description = "A scientist’s journey through alternate realities.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image10.jpeg",
                            ReleaseDate = new DateTime(2021, 6, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Echoes of Tomorrow",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("63b74640-2a18-4983-848e-baaf7f8719d5"),
                            Description = "An emotional drama tied to a pianist’s legacy.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image11.jpeg",
                            ReleaseDate = new DateTime(2016, 2, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Firelight Sonata",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("0cdc6b8a-2c18-435f-9f55-409e3f669d15"),
                            Description = "A war epic involving machines and mankind.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image12.jpeg",
                            ReleaseDate = new DateTime(2018, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Steel Giants",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("d2ed710d-9a3d-423f-b6fc-579d886a5336"),
                            Description = "A poetic indie film exploring childhood and loss.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image13.jpeg",
                            ReleaseDate = new DateTime(2019, 3, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Painted Skies",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("f44f4cb1-530a-4beb-abaa-8ac57caba443"),
                            Description = "A fantasy about a man who protects forgotten worlds.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image14.jpeg",
                            ReleaseDate = new DateTime(2020, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Archivist",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("b8f64ba1-1046-4d9b-a01f-dc4c20740ddc"),
                            Description = "A musical drama following a band’s rise to fame.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image15.jpeg",
                            ReleaseDate = new DateTime(2017, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Iron Melody",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("f9cc4f63-6893-48ae-bfb2-c9aefd5076c6"),
                            Description = "A dark thriller in a seemingly peaceful suburb.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image16.jpeg",
                            ReleaseDate = new DateTime(2018, 4, 13, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Shadow Over Town",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("d6b06619-41f6-49f8-af5e-bc64ff383ff5"),
                            Description = "A drama about childhood dreams and family.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image17.jpeg",
                            ReleaseDate = new DateTime(2015, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Paper Moons",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("235cc7ac-2090-485e-8572-f59229a9432e"),
                            Description = "An investigative drama with deep secrets.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image18.jpeg",
                            ReleaseDate = new DateTime(2017, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Under the Surface",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("9555d890-4763-4011-b243-4e046054d13b"),
                            Description = "Urban lives intertwined through a rooftop café.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image19.jpeg",
                            ReleaseDate = new DateTime(2015, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Skyline Stories",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("d8027469-1172-4792-aa38-ac245a68da81"),
                            Description = "A magician’s journey across dimensions.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image20.jpeg",
                            ReleaseDate = new DateTime(2021, 1, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dust & Mirrors",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("be66d9a7-4639-4851-8242-e1c9a4ec08f6"),
                            Description = "A historical drama in a pre-war aristocratic town.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image21.jpeg",
                            ReleaseDate = new DateTime(2018, 12, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Halcyon Row",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("06a7d48f-1ff0-4f13-a44b-b8091f582a5f"),
                            Description = "A culinary travelogue that mixes food and mystery.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image22.jpeg",
                            ReleaseDate = new DateTime(2019, 10, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Midnight Recipe",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("fe6e9d59-7fe4-4048-836d-af8503e2c443"),
                            Description = "A sci-fi thriller about communication from beyond.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image23.jpeg",
                            ReleaseDate = new DateTime(2020, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Cold Signal",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("f5449e66-3971-44ea-ba81-f422915956e9"),
                            Description = "Anthology series exploring alternate outcomes.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image24.jpeg",
                            ReleaseDate = new DateTime(2022, 9, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Echo Street",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("b4744445-2677-4aba-a374-b2a1ab0d951e"),
                            Description = "Stories told by street performers in Tokyo.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image25.jpeg",
                            ReleaseDate = new DateTime(2016, 1, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lanterns",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("d88f6066-33b2-4563-90aa-da7962444ab9"),
                            Description = "Police procedural with futuristic gadgets.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image26.jpeg",
                            ReleaseDate = new DateTime(2021, 3, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Redline Division",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("d00ce609-801d-4f5a-8053-af7da2f0d369"),
                            Description = "An artistic exploration of urban loneliness.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image27.jpeg",
                            ReleaseDate = new DateTime(2019, 6, 29, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fractured Light",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("60644f90-4158-4cf8-8860-053fbdffd01e"),
                            Description = "A time-travel drama with family stakes.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image28.jpeg",
                            ReleaseDate = new DateTime(2018, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Watchmaker",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("c30363b0-5301-4478-be53-dc117b5f0e0b"),
                            Description = "A docu-drama about dream studies and cases.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image29.jpeg",
                            ReleaseDate = new DateTime(2020, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dreampoint",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("4b417fb9-81e1-40cb-9ea8-ca59b654a822"),
                            Description = "A story of journalists uncovering corruption.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image30.jpeg",
                            ReleaseDate = new DateTime(2017, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Beacon Hill",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("7d486175-3d98-4708-a8d0-1a89ce784c6b"),
                            Description = "Neighbors trapped in parallel timelines.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image31.jpeg",
                            ReleaseDate = new DateTime(2016, 3, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Parallel Doors",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("0b5af27e-8324-4f79-801e-0e93168e5d89"),
                            Description = "Mysterious disappearances on an isolated island.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image32.jpeg",
                            ReleaseDate = new DateTime(2015, 11, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sea of Silence",
                            Type = "TVShow"
                        });
                });

            modelBuilder.Entity("Domain.Models.ContentCast", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CastId")
                        .HasColumnType("TEXT");

                    b.HasKey("ContentId", "CastId");

                    b.HasIndex("CastId");

                    b.ToTable("ContentCasts");
                });

            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewId");

                    b.HasIndex("ContentId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "Rating >= 1 AND Rating <= 5");
                        });
                });

            modelBuilder.Entity("Domain.Models.ContentCast", b =>
                {
                    b.HasOne("Domain.Models.Cast", "Cast")
                        .WithMany("ContentCasts")
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Content", "Content")
                        .WithMany("ContentCasts")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cast");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.HasOne("Domain.Models.Content", "Content")
                        .WithMany("Reviews")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Domain.Models.Cast", b =>
                {
                    b.Navigation("ContentCasts");
                });

            modelBuilder.Entity("Domain.Models.Content", b =>
                {
                    b.Navigation("ContentCasts");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
