// <auto-generated />
using System;
using EfcDataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfcDataAccess.Migrations
{
    [DbContext(typeof(MovieReviewEngineContext))]
    [Migration("20250704212815_SeedMore")]
    partial class SeedMore
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Domain.Models.Cast", b =>
                {
                    b.Property<Guid>("CastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CastId");

                    b.ToTable("Casts");
                });

            modelBuilder.Entity("Domain.Models.Content", b =>
                {
                    b.Property<Guid>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContentId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            ContentId = new Guid("6db1a7f1-a644-41ea-aab6-2fb4a8e93f8f"),
                            Description = "A romantic drama set during WWII in Casablanca.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image1.jpg",
                            ReleaseDate = new DateTime(1942, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Casablanca",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("a4ca86a7-9649-4708-a025-31bff1a6b3d6"),
                            Description = "A newspaper magnate’s rise and fall.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image2.jpg",
                            ReleaseDate = new DateTime(1941, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Citizen Kane",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("1de5d7df-b314-4432-ad05-c28c98b15367"),
                            Description = "A voyage through space and time.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image3.jpg",
                            ReleaseDate = new DateTime(1968, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "2001: A Space Odyssey",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("629cd4b7-f47f-4f3c-a39a-cd5e9cf2d778"),
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image4.jpg",
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("11105e76-b024-4d42-8363-ff0894f43b38"),
                            Description = "A great white shark terrorizes a summer resort town.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image5.jpg",
                            ReleaseDate = new DateTime(1975, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jaws",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("ad063a70-015a-4445-80d3-aeabb9777af4"),
                            Description = "A lost alien befriends a boy in suburbia.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image6.jpg",
                            ReleaseDate = new DateTime(1982, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "E.T. the Extra-Terrestrial",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("81ff37c5-4d1b-498e-92df-b961b38367c1"),
                            Description = "The story of Oskar Schindler and his efforts to save Jews during the Holocaust.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image7.jpg",
                            ReleaseDate = new DateTime(1993, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindler's List",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("1f333330-72ce-482a-81c0-f7ac7104f146"),
                            Description = "A hacker discovers reality is an illusion.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image8.jpg",
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("154a102f-f817-4a91-8d04-00edf6e0c92a"),
                            Description = "A Roman general becomes a gladiator.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image9.jpg",
                            ReleaseDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gladiator",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("3aad174d-b3dc-4b8c-a773-d374ca467b93"),
                            Description = "Batman faces the Joker.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image10.jpg",
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("78d37b48-7605-47a8-b0fb-c64246f9ceec"),
                            Description = "A thief who steals corporate secrets through dream-sharing.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image11.jpg",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("cc6b803e-655c-4664-944b-7604bb1dace5"),
                            Description = "A free black man is kidnapped and sold into slavery.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image12.jpg",
                            ReleaseDate = new DateTime(2013, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "12 Years a Slave",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("918ab0b5-dbde-49a2-bd3c-c865358dbec7"),
                            Description = "Post-apocalyptic road war.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image13.jpg",
                            ReleaseDate = new DateTime(2015, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mad Max: Fury Road",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("4df53c3b-9185-4466-a0e3-4b10001b77ed"),
                            Description = "A young black man grows up in Miami.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image14.jpg",
                            ReleaseDate = new DateTime(2016, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Moonlight",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("0d4a6608-f186-4025-8391-7fd4a9245f77"),
                            Description = "Poor family infiltrates a wealthy household.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image15.jpg",
                            ReleaseDate = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Parasite",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("c31c4c4c-7fd5-4fea-9923-6680eab39441"),
                            Description = "A woman lives as a van-dwelling modern nomad.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image16.jpg",
                            ReleaseDate = new DateTime(2020, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nomadland",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("7d63987d-4afa-46e5-a012-465a78c174ab"),
                            Description = "A son of a noble family leads a rebellion on a desert planet.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image17.jpg",
                            ReleaseDate = new DateTime(2021, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dune",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("0471d650-fbe4-457e-9d1b-05766b859aa6"),
                            Description = "A multiverse adventure through family and identity.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image18.jpg",
                            ReleaseDate = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Everything Everywhere All at Once",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("96d738fe-b10b-4736-9811-fd1005b8a936"),
                            Description = "A naval aviator returns as a flight instructor.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image19.jpg",
                            ReleaseDate = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Gun: Maverick",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("82db15d2-101b-479f-8c7e-a87d443a833b"),
                            Description = "The story of the father of the atomic bomb.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image20.jpg",
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oppenheimer",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("2e085d5b-c59e-4462-9a46-ae337a300a3d"),
                            Description = "A journey of self-discovery in Barbie Land.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image21.jpg",
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Barbie",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("3cab5499-4e5c-4269-abc1-70caadefca20"),
                            Description = "A true-crime saga in 1920s Oklahoma.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image22.jpg",
                            ReleaseDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Killers of the Flower Moon",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("58913189-c7fa-427a-b8f5-0e30d5bac26a"),
                            Description = "A Victorian tale of a woman brought back to life.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image23.jpg",
                            ReleaseDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Poor Things",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("8888ca05-7db4-48e2-8133-b2d9c92a2ed9"),
                            Description = "Miles Morales returns for more multiverse action.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image24.jpg",
                            ReleaseDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spider-Man: Across the Spider‑Verse",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("7059bf22-5624-47c9-bddc-7d5114c05bfa"),
                            Description = "A reclusive teacher tries to reconnect with his daughter.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image25.jpg",
                            ReleaseDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Whale",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("153da6a7-2439-45a3-85ce-e62f894e7ec5"),
                            Description = "A rancher responds brutally to a new marriage.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image26.jpg",
                            ReleaseDate = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Power of the Dog",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("5669099e-c4dc-4e50-84f6-b36151bcb68a"),
                            Description = "Dramatization of a famous protest trial.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image27.jpg",
                            ReleaseDate = new DateTime(2020, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Trial of the Chicago 7",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("2a93405a-832e-4172-a8f4-f3829e9f7b56"),
                            Description = "A musician travels from Earth to the afterlife.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image28.jpg",
                            ReleaseDate = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Soul",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("28b6c902-a342-49e5-be1d-09ba7d22fe62"),
                            Description = "Post-apocalyptic survival drama (film adaption placeholder).",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image29.jpg",
                            ReleaseDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last of Us",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("8b8a71c5-d8cd-4a45-aaed-1fb640e49777"),
                            Description = "A mafia boss tries to balance crime and family.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image1.jpg",
                            ReleaseDate = new DateTime(1999, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sopranos",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("77a18b78-6fa1-4a0c-8e3c-a3b26052b0a4"),
                            Description = "An in-depth look into crime, bureaucracy and society in Baltimore.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image2.jpg",
                            ReleaseDate = new DateTime(2002, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Wire",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("311dcda6-8577-49bc-847b-5078f7aad167"),
                            Description = "A chemistry teacher becomes a meth kingpin.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image3.jpg",
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Breaking Bad",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("c398eff3-d9d8-4c06-9271-5b38d964e588"),
                            Description = "Noble families vie for power in a mythical land.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image4.jpg",
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game of Thrones",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("f0730d03-b5fe-4c5c-9b14-5ea9813299e3"),
                            Description = "Kids uncover government secrets and supernatural horrors in 1980s Indiana.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image5.jpg",
                            ReleaseDate = new DateTime(2016, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stranger Things",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("7c6675e0-974f-499d-879e-5798ec6b029e"),
                            Description = "A dramatized history of the British royal family.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image6.jpg",
                            ReleaseDate = new DateTime(2016, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Crown",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("54695b94-9240-497f-8bf2-8d839d2f7e76"),
                            Description = "A lone bounty hunter in the Star Wars universe.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image7.jpg",
                            ReleaseDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Mandalorian",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("1114d15b-9e9b-464f-8060-55f5767d81fe"),
                            Description = "A mockumentary about office workers in Scranton, PA.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image8.jpg",
                            ReleaseDate = new DateTime(2005, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Office",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("0c4dc2c0-2f5f-4f8b-b3fb-a1604d4cef6f"),
                            Description = "Six friends navigating life in New York City.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image9.jpg",
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Friends",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("daae7734-5efd-4bcc-9a29-7be7b46eb862"),
                            Description = "A show about nothing centered on a quirky group of friends.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image10.jpg",
                            ReleaseDate = new DateTime(1989, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Seinfeld",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("9be48317-007d-4ddb-82c3-6720450d39a2"),
                            Description = "The story of criminal lawyer Saul Goodman before Breaking Bad.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image11.jpg",
                            ReleaseDate = new DateTime(2015, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Better Call Saul",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("26d2de1e-06ff-4cd0-99cd-0dd83b74a47d"),
                            Description = "A group takes on corrupt superheroes.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image12.jpg",
                            ReleaseDate = new DateTime(2019, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Boys",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("3955fea2-d1cf-4b3b-b3f3-98477fb53f57"),
                            Description = "A hardened survivor escorts a girl across post-apocalyptic America.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image13.jpg",
                            ReleaseDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last of Us",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("7096732d-96c9-476e-8963-40659d44444e"),
                            Description = "Desperate contestants play deadly children's games for money.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image14.jpg",
                            ReleaseDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Squid Game",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("08c9454d-2bf8-4edb-b55e-8c26bffa6051"),
                            Description = "A prequel to Game of Thrones about House Targaryen.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image15.jpg",
                            ReleaseDate = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "House of the Dragon",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("2ebf88af-8472-444a-99db-2f2831f062c6"),
                            Description = "A gangster family in post-WWI Birmingham, England.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image16.jpg",
                            ReleaseDate = new DateTime(2013, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Peaky Blinders",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("8bba928f-b193-492b-a50c-0a1a5cfb758a"),
                            Description = "A dystopian society where women are forced into servitude.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image17.jpg",
                            ReleaseDate = new DateTime(2017, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Handmaid's Tale",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("8a5d3d33-ff72-4f81-b76a-62fb28f5692c"),
                            Description = "A theme park where robots develop consciousness.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image18.jpg",
                            ReleaseDate = new DateTime(2016, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Westworld",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("9b8ea8eb-eb20-46f3-9cf7-edf65ed4d4a8"),
                            Description = "A dramatization of the 1986 nuclear disaster.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image19.jpg",
                            ReleaseDate = new DateTime(2019, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chernobyl",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("46a9c358-3321-4c7e-8861-05829fcdde03"),
                            Description = "A young chess prodigy rises amid addiction and competition.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image20.jpg",
                            ReleaseDate = new DateTime(2020, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Queen's Gambit",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("fc05906d-b5b0-481b-b8c0-0e92df8a8985"),
                            Description = "A German sci-fi thriller involving time travel.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image21.jpg",
                            ReleaseDate = new DateTime(2017, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dark",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("c625de9b-8736-4089-bfe9-56027cdc0772"),
                            Description = "Anthology series exploring technology's dark side.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image22.jpg",
                            ReleaseDate = new DateTime(2011, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Mirror",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("f5e54884-6cd9-491d-8828-397c7759d8b7"),
                            Description = "Crime stories in the Midwest with dark humor.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image23.jpg",
                            ReleaseDate = new DateTime(2014, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fargo",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("95f86751-3138-4f19-a47d-a2b40edd6fa1"),
                            Description = "A family launders drug money in Missouri.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image24.jpg",
                            ReleaseDate = new DateTime(2017, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ozark",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("7bf9aa8c-b052-496f-8e77-f8ed45ffd1f3"),
                            Description = "A powerful family's battle for control of a media empire.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image25.jpg",
                            ReleaseDate = new DateTime(2018, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Succession",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("f09573b0-13b4-474d-a54a-a92faacae0c1"),
                            Description = "A kind-hearted coach leads a UK soccer team.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image26.jpg",
                            ReleaseDate = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ted Lasso",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("517ffc8e-5767-45e8-a60b-e83e97357c5e"),
                            Description = "The god of mischief causes chaos across timelines.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image27.jpg",
                            ReleaseDate = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Loki",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("60725a35-292d-4bd3-9bc2-759d0fb45734"),
                            Description = "Superpowered couple trapped in a sitcom reality.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image28.jpg",
                            ReleaseDate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "WandaVision",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("cd6dc69c-f109-4af3-babc-cd5d5513fba6"),
                            Description = "A chef returns to run his family’s sandwich shop in Chicago.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image29.jpg",
                            ReleaseDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Bear",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("570df853-8df6-474d-a7ab-331e31501049"),
                            Description = "Wednesday Addams navigates high school and murder mysteries.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image30.jpg",
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wednesday",
                            Type = "TVShow"
                        });
                });

            modelBuilder.Entity("Domain.Models.ContentCast", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CastId")
                        .HasColumnType("TEXT");

                    b.HasKey("ContentId", "CastId");

                    b.HasIndex("CastId");

                    b.ToTable("ContentCasts");
                });

            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewId");

                    b.HasIndex("ContentId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "Rating >= 1 AND Rating <= 5");
                        });
                });

            modelBuilder.Entity("Domain.Models.ContentCast", b =>
                {
                    b.HasOne("Domain.Models.Cast", "Cast")
                        .WithMany("ContentCasts")
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Content", "Content")
                        .WithMany("ContentCasts")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cast");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.HasOne("Domain.Models.Content", "Content")
                        .WithMany("Reviews")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Domain.Models.Cast", b =>
                {
                    b.Navigation("ContentCasts");
                });

            modelBuilder.Entity("Domain.Models.Content", b =>
                {
                    b.Navigation("ContentCasts");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
