// <auto-generated />
using System;
using EfcDataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EfcDataAccess.Migrations
{
    [DbContext(typeof(MovieReviewEngineContext))]
    [Migration("20250706161602_SeedCastContent3")]
    partial class SeedCastContent3
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("Domain.Models.Cast", b =>
                {
                    b.Property<Guid>("CastId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("CastId");

                    b.ToTable("Casts");

                    b.HasData(
                        new
                        {
                            CastId = new Guid("f7b6e9d0-1f24-4c58-a5d3-111111111111"),
                            Name = "Keanu Reeves"
                        },
                        new
                        {
                            CastId = new Guid("e2c1f1a7-4a56-4eab-bd2d-222222222222"),
                            Name = "Carrie-Anne Moss"
                        },
                        new
                        {
                            CastId = new Guid("d9f3a7d3-2b16-4d4d-b8b8-333333333333"),
                            Name = "Laurence Fishburne"
                        },
                        new
                        {
                            CastId = new Guid("a8d3f35c-c7d4-4a88-9111-444444444444"),
                            Name = "Jennifer Aniston"
                        },
                        new
                        {
                            CastId = new Guid("b1d1f57e-66f0-4b1d-bb1c-555555555555"),
                            Name = "Courteney Cox"
                        },
                        new
                        {
                            CastId = new Guid("c7d3a5b1-e4b7-4eae-8d6e-666666666666"),
                            Name = "Matthew Perry"
                        },
                        new
                        {
                            CastId = new Guid("2e70b7a4-84e0-43a6-93b8-777777777777"),
                            Name = "Marlon Brando"
                        },
                        new
                        {
                            CastId = new Guid("bbfc7892-d752-4d9f-92a2-888888888888"),
                            Name = "Al Pacino"
                        },
                        new
                        {
                            CastId = new Guid("975f7c8c-4f9c-4ebd-8284-999999999999"),
                            Name = "James Caan"
                        },
                        new
                        {
                            CastId = new Guid("84d3f779-14f1-4c88-b9d7-aaaaaaaaaaaa"),
                            Name = "Bryan Cranston"
                        },
                        new
                        {
                            CastId = new Guid("b3f8c7aa-43c7-43ad-b765-bbbbbbbbbbbb"),
                            Name = "Aaron Paul"
                        },
                        new
                        {
                            CastId = new Guid("96e63e2d-7c65-4d44-984e-cccccccccccc"),
                            Name = "Anna Gunn"
                        },
                        new
                        {
                            CastId = new Guid("38a62e4d-8bca-4ec6-9f27-dddddddddddd"),
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            CastId = new Guid("a1b2c3d4-5e6f-4a7b-8c9d-eeeeeeeeeeee"),
                            Name = "Joseph Gordon-Levitt"
                        },
                        new
                        {
                            CastId = new Guid("f1e2d3c4-b5a6-4789-9012-ffffffffffff"),
                            Name = "Ellen Page"
                        },
                        new
                        {
                            CastId = new Guid("12345678-9abc-def0-1234-111111111111"),
                            Name = "Millie Bobby Brown"
                        },
                        new
                        {
                            CastId = new Guid("23456789-abcd-ef01-2345-222222222222"),
                            Name = "Finn Wolfhard"
                        },
                        new
                        {
                            CastId = new Guid("3456789a-bcde-f012-3456-333333333333"),
                            Name = "Winona Ryder"
                        },
                        new
                        {
                            CastId = new Guid("10000000-0000-0000-0000-000000000001"),
                            Name = "Emilia Clarke"
                        },
                        new
                        {
                            CastId = new Guid("10000000-0000-0000-0000-000000000002"),
                            Name = "Kit Harington"
                        },
                        new
                        {
                            CastId = new Guid("10000000-0000-0000-0000-000000000003"),
                            Name = "Peter Dinklage"
                        },
                        new
                        {
                            CastId = new Guid("20000000-0000-0000-0000-000000000001"),
                            Name = "Steve Carell"
                        },
                        new
                        {
                            CastId = new Guid("20000000-0000-0000-0000-000000000002"),
                            Name = "John Krasinski"
                        },
                        new
                        {
                            CastId = new Guid("20000000-0000-0000-0000-000000000003"),
                            Name = "Jenna Fischer"
                        },
                        new
                        {
                            CastId = new Guid("70000000-0000-0000-0000-000000000001"),
                            Name = "Bryce Dallas Howard"
                        },
                        new
                        {
                            CastId = new Guid("70000000-0000-0000-0000-000000000002"),
                            Name = "Jon Hamm"
                        },
                        new
                        {
                            CastId = new Guid("70000000-0000-0000-0000-000000000003"),
                            Name = "Mackenzie Davis"
                        },
                        new
                        {
                            CastId = new Guid("80000000-0000-0000-0000-000000000001"),
                            Name = "Claire Foy"
                        },
                        new
                        {
                            CastId = new Guid("80000000-0000-0000-0000-000000000002"),
                            Name = "Matt Smith"
                        },
                        new
                        {
                            CastId = new Guid("80000000-0000-0000-0000-000000000003"),
                            Name = "Olivia Colman"
                        },
                        new
                        {
                            CastId = new Guid("b0000001-0000-0000-0000-000000000001"),
                            Name = "Evan Rachel Wood"
                        },
                        new
                        {
                            CastId = new Guid("b0000002-0000-0000-0000-000000000002"),
                            Name = "Thandie Newton"
                        },
                        new
                        {
                            CastId = new Guid("b0000003-0000-0000-0000-000000000003"),
                            Name = "Jeffrey Wright"
                        },
                        new
                        {
                            CastId = new Guid("d0000001-0000-0000-0000-000000000001"),
                            Name = "Cillian Murphy"
                        },
                        new
                        {
                            CastId = new Guid("d0000002-0000-0000-0000-000000000002"),
                            Name = "Helen McCrory"
                        },
                        new
                        {
                            CastId = new Guid("d0000003-0000-0000-0000-000000000003"),
                            Name = "Paul Anderson"
                        },
                        new
                        {
                            CastId = new Guid("e0000001-0000-0000-0000-000000000001"),
                            Name = "Pedro Pascal"
                        },
                        new
                        {
                            CastId = new Guid("e0000002-0000-0000-0000-000000000002"),
                            Name = "Gina Carano"
                        },
                        new
                        {
                            CastId = new Guid("e0000003-0000-0000-0000-000000000003"),
                            Name = "Carl Weathers"
                        },
                        new
                        {
                            CastId = new Guid("a1000001-0000-0000-0000-000000000001"),
                            Name = "Karl Urban"
                        },
                        new
                        {
                            CastId = new Guid("a1000002-0000-0000-0000-000000000002"),
                            Name = "Jack Quaid"
                        },
                        new
                        {
                            CastId = new Guid("a1000003-0000-0000-0000-000000000003"),
                            Name = "Antony Starr"
                        },
                        new
                        {
                            CastId = new Guid("a2000001-0000-0000-0000-000000000001"),
                            Name = "Elizabeth Olsen"
                        },
                        new
                        {
                            CastId = new Guid("a2000002-0000-0000-0000-000000000002"),
                            Name = "Paul Bettany"
                        },
                        new
                        {
                            CastId = new Guid("a2000003-0000-0000-0000-000000000003"),
                            Name = "Kathryn Hahn"
                        },
                        new
                        {
                            CastId = new Guid("a2000004-0000-0000-0000-000000000004"),
                            Name = "Brian Cox"
                        },
                        new
                        {
                            CastId = new Guid("a2000005-0000-0000-0000-000000000005"),
                            Name = "Jeremy Strong"
                        },
                        new
                        {
                            CastId = new Guid("a2000006-0000-0000-0000-000000000006"),
                            Name = "Sarah Snook"
                        },
                        new
                        {
                            CastId = new Guid("a2000007-0000-0000-0000-000000000007"),
                            Name = "Trevante Rhodes"
                        },
                        new
                        {
                            CastId = new Guid("a2000008-0000-0000-0000-000000000008"),
                            Name = "Mahershala Ali"
                        },
                        new
                        {
                            CastId = new Guid("a2000009-0000-0000-0000-000000000009"),
                            Name = "Naomie Harris"
                        },
                        new
                        {
                            CastId = new Guid("a2000010-0000-0000-0000-000000000010"),
                            Name = "Jerry Seinfeld"
                        },
                        new
                        {
                            CastId = new Guid("a2000011-0000-0000-0000-000000000011"),
                            Name = "Julia Louis-Dreyfus"
                        },
                        new
                        {
                            CastId = new Guid("a2000012-0000-0000-0000-000000000012"),
                            Name = "Michael Richards"
                        },
                        new
                        {
                            CastId = new Guid("a2000013-0000-0000-0000-000000000013"),
                            Name = "Leonardo DiCaprio"
                        },
                        new
                        {
                            CastId = new Guid("a2000014-0000-0000-0000-000000000014"),
                            Name = "Robert De Niro"
                        },
                        new
                        {
                            CastId = new Guid("a2000015-0000-0000-0000-000000000015"),
                            Name = "Jesse Plemons"
                        },
                        new
                        {
                            CastId = new Guid("a2000019-0000-0000-0000-000000000019"),
                            Name = "Dominic West"
                        },
                        new
                        {
                            CastId = new Guid("a2000020-0000-0000-0000-000000000020"),
                            Name = "Idris Elba"
                        },
                        new
                        {
                            CastId = new Guid("a2000021-0000-0000-0000-000000000021"),
                            Name = "Michael K. Williams"
                        },
                        new
                        {
                            CastId = new Guid("a2000022-0000-0000-0000-000000000022"),
                            Name = "Tom Hardy"
                        },
                        new
                        {
                            CastId = new Guid("a2000023-0000-0000-0000-000000000023"),
                            Name = "Charlize Theron"
                        },
                        new
                        {
                            CastId = new Guid("a2000024-0000-0000-0000-000000000024"),
                            Name = "Nicholas Hoult"
                        },
                        new
                        {
                            CastId = new Guid("a2000025-0000-0000-0000-000000000025"),
                            Name = "Tom Cruise"
                        },
                        new
                        {
                            CastId = new Guid("a2000026-0000-0000-0000-000000000026"),
                            Name = "Miles Teller"
                        },
                        new
                        {
                            CastId = new Guid("a2000027-0000-0000-0000-000000000027"),
                            Name = "Jennifer Connelly"
                        },
                        new
                        {
                            CastId = new Guid("a2000028-0000-0000-0000-000000000028"),
                            Name = "Cillian Murphy"
                        },
                        new
                        {
                            CastId = new Guid("a2000029-0000-0000-0000-000000000029"),
                            Name = "Emily Blunt"
                        },
                        new
                        {
                            CastId = new Guid("a2000030-0000-0000-0000-000000000030"),
                            Name = "Matt Damon"
                        },
                        new
                        {
                            CastId = new Guid("a2000040-0000-0000-0000-000000000040"),
                            Name = "Margot Robbie"
                        },
                        new
                        {
                            CastId = new Guid("a2000041-0000-0000-0000-000000000041"),
                            Name = "Ryan Gosling"
                        },
                        new
                        {
                            CastId = new Guid("a2000042-0000-0000-0000-000000000042"),
                            Name = "America Ferrera"
                        },
                        new
                        {
                            CastId = new Guid("f0000001-0000-0000-0000-000000000001"),
                            Name = "Chiwetel Ejiofor"
                        },
                        new
                        {
                            CastId = new Guid("f0000031-0000-0000-0000-000000000031"),
                            Name = "Michael Fassbender"
                        },
                        new
                        {
                            CastId = new Guid("f0000002-0000-0000-0000-000000000002"),
                            Name = "Lee Jung-jae"
                        },
                        new
                        {
                            CastId = new Guid("f0000032-0000-0000-0000-000000000032"),
                            Name = "HoYeon Jung"
                        },
                        new
                        {
                            CastId = new Guid("f0000003-0000-0000-0000-000000000003"),
                            Name = "Orson Welles"
                        },
                        new
                        {
                            CastId = new Guid("f0000033-0000-0000-0000-000000000033"),
                            Name = "Joseph Cotten"
                        },
                        new
                        {
                            CastId = new Guid("f0000004-0000-0000-0000-000000000004"),
                            Name = "Jared Harris"
                        },
                        new
                        {
                            CastId = new Guid("f0000034-0000-0000-0000-000000000034"),
                            Name = "Stellan Skarsgård"
                        },
                        new
                        {
                            CastId = new Guid("f0000005-0000-0000-0000-000000000005"),
                            Name = "Jeremy Allen White"
                        },
                        new
                        {
                            CastId = new Guid("f0000035-0000-0000-0000-000000000035"),
                            Name = "Ayo Edebiri"
                        },
                        new
                        {
                            CastId = new Guid("f0000006-0000-0000-0000-000000000006"),
                            Name = "Louis Hofmann"
                        },
                        new
                        {
                            CastId = new Guid("f0000036-0000-0000-0000-000000000036"),
                            Name = "Lisa Vicari"
                        },
                        new
                        {
                            CastId = new Guid("f0000007-0000-0000-0000-000000000007"),
                            Name = "Bella Ramsey"
                        },
                        new
                        {
                            CastId = new Guid("f0000037-0000-0000-0000-000000000037"),
                            Name = "Pedro Pascal"
                        },
                        new
                        {
                            CastId = new Guid("f0000008-0000-0000-0000-000000000008"),
                            Name = "Benedict Cumberbatch"
                        },
                        new
                        {
                            CastId = new Guid("f0000038-0000-0000-0000-000000000038"),
                            Name = "Kirsten Dunst"
                        },
                        new
                        {
                            CastId = new Guid("f0000009-0000-0000-0000-000000000009"),
                            Name = "Sacha Baron Cohen"
                        },
                        new
                        {
                            CastId = new Guid("f0000039-0000-0000-0000-000000000039"),
                            Name = "Eddie Redmayne"
                        },
                        new
                        {
                            CastId = new Guid("f0000010-0000-0000-0000-000000000010"),
                            Name = "Brendan Fraser"
                        },
                        new
                        {
                            CastId = new Guid("f0000040-0000-0000-0000-000000000040"),
                            Name = "Sadie Sink"
                        },
                        new
                        {
                            CastId = new Guid("f0000011-0000-0000-0000-000000000011"),
                            Name = "Jason Bateman"
                        },
                        new
                        {
                            CastId = new Guid("f0000041-0000-0000-0000-000000000041"),
                            Name = "Laura Linney"
                        },
                        new
                        {
                            CastId = new Guid("f0000012-0000-0000-0000-000000000012"),
                            Name = "Jenna Ortega"
                        },
                        new
                        {
                            CastId = new Guid("f0000042-0000-0000-0000-000000000042"),
                            Name = "Catherine Zeta-Jones"
                        },
                        new
                        {
                            CastId = new Guid("f0000013-0000-0000-0000-000000000013"),
                            Name = "Emma Stone"
                        },
                        new
                        {
                            CastId = new Guid("f0000043-0000-0000-0000-000000000043"),
                            Name = "Mark Ruffalo"
                        },
                        new
                        {
                            CastId = new Guid("f0000014-0000-0000-0000-000000000014"),
                            Name = "Jamie Foxx"
                        },
                        new
                        {
                            CastId = new Guid("f0000044-0000-0000-0000-000000000044"),
                            Name = "Tina Fey"
                        },
                        new
                        {
                            CastId = new Guid("f0000015-0000-0000-0000-000000000015"),
                            Name = "Shameik Moore"
                        },
                        new
                        {
                            CastId = new Guid("f0000045-0000-0000-0000-000000000045"),
                            Name = "Hailee Steinfeld"
                        },
                        new
                        {
                            CastId = new Guid("f0000016-0000-0000-0000-000000000016"),
                            Name = "Anya Taylor-Joy"
                        },
                        new
                        {
                            CastId = new Guid("f0000046-0000-0000-0000-000000000046"),
                            Name = "Thomas Brodie-Sangster"
                        },
                        new
                        {
                            CastId = new Guid("f0000017-0000-0000-0000-000000000017"),
                            Name = "Emma D'Arcy"
                        },
                        new
                        {
                            CastId = new Guid("f0000047-0000-0000-0000-000000000047"),
                            Name = "Matt Smith"
                        },
                        new
                        {
                            CastId = new Guid("f0000018-0000-0000-0000-000000000018"),
                            Name = "Bob Odenkirk"
                        },
                        new
                        {
                            CastId = new Guid("f0000048-0000-0000-0000-000000000048"),
                            Name = "Rhea Seehorn"
                        },
                        new
                        {
                            CastId = new Guid("f0000019-0000-0000-0000-000000000019"),
                            Name = "Frances McDormand"
                        },
                        new
                        {
                            CastId = new Guid("f0000049-0000-0000-0000-000000000049"),
                            Name = "David Strathairn"
                        },
                        new
                        {
                            CastId = new Guid("f0000020-0000-0000-0000-000000000020"),
                            Name = "Humphrey Bogart"
                        },
                        new
                        {
                            CastId = new Guid("f0000050-0000-0000-0000-000000000050"),
                            Name = "Ingrid Bergman"
                        },
                        new
                        {
                            CastId = new Guid("f0000021-0000-0000-0000-000000000021"),
                            Name = "Liam Neeson"
                        },
                        new
                        {
                            CastId = new Guid("f0000051-0000-0000-0000-000000000051"),
                            Name = "Ralph Fiennes"
                        },
                        new
                        {
                            CastId = new Guid("f0000022-0000-0000-0000-000000000022"),
                            Name = "James Gandolfini"
                        },
                        new
                        {
                            CastId = new Guid("f0000052-0000-0000-0000-000000000052"),
                            Name = "Edie Falco"
                        },
                        new
                        {
                            CastId = new Guid("f0000023-0000-0000-0000-000000000023"),
                            Name = "Jason Sudeikis"
                        },
                        new
                        {
                            CastId = new Guid("f0000053-0000-0000-0000-000000000053"),
                            Name = "Hannah Waddingham"
                        },
                        new
                        {
                            CastId = new Guid("f0000024-0000-0000-0000-000000000024"),
                            Name = "Russell Crowe"
                        },
                        new
                        {
                            CastId = new Guid("f0000054-0000-0000-0000-000000000054"),
                            Name = "Joaquin Phoenix"
                        },
                        new
                        {
                            CastId = new Guid("f0000025-0000-0000-0000-000000000025"),
                            Name = "Henry Thomas"
                        },
                        new
                        {
                            CastId = new Guid("f0000055-0000-0000-0000-000000000055"),
                            Name = "Drew Barrymore"
                        },
                        new
                        {
                            CastId = new Guid("f0000026-0000-0000-0000-000000000026"),
                            Name = "Timothée Chalamet"
                        },
                        new
                        {
                            CastId = new Guid("f0000056-0000-0000-0000-000000000056"),
                            Name = "Zendaya"
                        },
                        new
                        {
                            CastId = new Guid("f0000027-0000-0000-0000-000000000027"),
                            Name = "Frances McDormand"
                        },
                        new
                        {
                            CastId = new Guid("f0000057-0000-0000-0000-000000000057"),
                            Name = "William H. Macy"
                        },
                        new
                        {
                            CastId = new Guid("f0000028-0000-0000-0000-000000000028"),
                            Name = "Roy Scheider"
                        },
                        new
                        {
                            CastId = new Guid("f0000058-0000-0000-0000-000000000058"),
                            Name = "Richard Dreyfuss"
                        });
                });

            modelBuilder.Entity("Domain.Models.Content", b =>
                {
                    b.Property<Guid>("ContentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageURL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContentId");

                    b.ToTable("Contents");

                    b.HasData(
                        new
                        {
                            ContentId = new Guid("0cfd88e9-3dd4-47bb-9c92-d3036285d487"),
                            Description = "A romantic drama set during WWII in Casablanca.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image1.jpg",
                            ReleaseDate = new DateTime(1942, 11, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Casablanca",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("f9af5ac8-3958-4921-bbad-92fc78c96c15"),
                            Description = "A newspaper magnate’s rise and fall.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image2.jpg",
                            ReleaseDate = new DateTime(1941, 5, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Citizen Kane",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("4df096f1-a0aa-4f9a-875b-b6d84be1c803"),
                            Description = "A voyage through space and time.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image3.jpg",
                            ReleaseDate = new DateTime(1968, 4, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "2001: A Space Odyssey",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("e7a26c01-14cf-4d7f-9e6e-f8b479de9ee9"),
                            Description = "The aging patriarch of an organized crime dynasty transfers control to his reluctant son.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image4.jpg",
                            ReleaseDate = new DateTime(1972, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Godfather",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("7efb6fc8-3e69-40c0-ab42-c9b27aad567c"),
                            Description = "A great white shark terrorizes a summer resort town.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image5.jpg",
                            ReleaseDate = new DateTime(1975, 6, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Jaws",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("bf02ebeb-3437-430d-9d3f-6e30b1330686"),
                            Description = "A lost alien befriends a boy in suburbia.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image6.jpg",
                            ReleaseDate = new DateTime(1982, 6, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "E.T. the Extra-Terrestrial",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("ed24da88-cbfd-490a-b525-af07fa3c438c"),
                            Description = "The story of Oskar Schindler and his efforts to save Jews during the Holocaust.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image7.jpg",
                            ReleaseDate = new DateTime(1993, 12, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Schindler's List",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("c431d325-9ca3-4160-8776-5a464953d429"),
                            Description = "A hacker discovers reality is an illusion.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image8.jpg",
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("591a1985-d8e9-4d8c-90d5-73a1ebbe3c94"),
                            Description = "A Roman general becomes a gladiator.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image9.jpg",
                            ReleaseDate = new DateTime(2000, 5, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Gladiator",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("54164c35-ac52-444d-aa19-22c2678402c6"),
                            Description = "Batman faces the Joker.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image10.jpg",
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("ecb09277-5bd4-4e82-b8bc-dd00e0c3f6b5"),
                            Description = "A thief who steals corporate secrets through dream-sharing.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image11.jpg",
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("f178ea48-e037-4c6f-aa7b-d96d7f570e78"),
                            Description = "A free black man is kidnapped and sold into slavery.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image12.jpg",
                            ReleaseDate = new DateTime(2013, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "12 Years a Slave",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("dd5b73c9-151a-4c0d-b2f8-a49dbb13d868"),
                            Description = "Post-apocalyptic road war.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image13.jpg",
                            ReleaseDate = new DateTime(2015, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Mad Max: Fury Road",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("0a29e8c7-ae78-43b4-9f46-d4476ec2c913"),
                            Description = "A young black man grows up in Miami.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image14.jpg",
                            ReleaseDate = new DateTime(2016, 10, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Moonlight",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("c875f04e-727b-4bbb-9d26-6f0c0fa7c6d3"),
                            Description = "Poor family infiltrates a wealthy household.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image15.jpg",
                            ReleaseDate = new DateTime(2019, 5, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Parasite",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("a19c9c19-4bcb-4012-841e-65684308338d"),
                            Description = "A woman lives as a van-dwelling modern nomad.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image16.jpg",
                            ReleaseDate = new DateTime(2020, 2, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Nomadland",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("1f133a10-6439-408f-b758-e59febd010be"),
                            Description = "A son of a noble family leads a rebellion on a desert planet.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image17.jpg",
                            ReleaseDate = new DateTime(2021, 10, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dune",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("fd31d9c5-4ed4-4afd-b690-2ce1729691fe"),
                            Description = "A multiverse adventure through family and identity.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image18.jpg",
                            ReleaseDate = new DateTime(2022, 3, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Everything Everywhere All at Once",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("ea61a7f8-81c1-4de9-8b95-8ca5372e4c49"),
                            Description = "A naval aviator returns as a flight instructor.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image19.jpg",
                            ReleaseDate = new DateTime(2022, 5, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Top Gun: Maverick",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("e1eb4251-7a0b-406d-84fc-c22dee281fe4"),
                            Description = "The story of the father of the atomic bomb.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image20.jpg",
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Oppenheimer",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("4ea3431e-0031-4f3f-8984-4b000dca25cd"),
                            Description = "A journey of self-discovery in Barbie Land.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image21.jpg",
                            ReleaseDate = new DateTime(2023, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Barbie",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("fd655b0a-61f1-4470-9444-f950b92ee17a"),
                            Description = "A true-crime saga in 1920s Oklahoma.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image22.jpg",
                            ReleaseDate = new DateTime(2023, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Killers of the Flower Moon",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("e21acfd9-a7e9-4f16-b1bf-b65a7f66b1e6"),
                            Description = "A Victorian tale of a woman brought back to life.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image23.jpg",
                            ReleaseDate = new DateTime(2023, 12, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Poor Things",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("7f3381be-d130-4c24-b6e6-4f200a13a9ed"),
                            Description = "Miles Morales returns for more multiverse action.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image24.jpg",
                            ReleaseDate = new DateTime(2023, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Spider-Man: Across the Spider‑Verse",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("61820f2e-dd92-40ec-8548-98b578cabd05"),
                            Description = "A reclusive teacher tries to reconnect with his daughter.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image25.jpg",
                            ReleaseDate = new DateTime(2022, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Whale",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("9cfebc12-d208-46a8-a744-99fc08a0574f"),
                            Description = "A rancher responds brutally to a new marriage.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image26.jpg",
                            ReleaseDate = new DateTime(2021, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Power of the Dog",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("b464f02f-7a27-4cea-877b-062a7dd9dfdc"),
                            Description = "Dramatization of a famous protest trial.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image27.jpg",
                            ReleaseDate = new DateTime(2020, 9, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Trial of the Chicago 7",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("6e8b6fd3-2ab6-4ffc-b4b9-2bcc660e6e62"),
                            Description = "A musician travels from Earth to the afterlife.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image28.jpg",
                            ReleaseDate = new DateTime(2020, 12, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Soul",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("7a9f3ac9-ddf7-4289-8351-a936e6c02a56"),
                            Description = "Post-apocalyptic survival drama (film adaption placeholder).",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/movie-image29.jpg",
                            ReleaseDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last of Us",
                            Type = "Movie"
                        },
                        new
                        {
                            ContentId = new Guid("06f61290-9420-4a7a-8a03-26ef4fd5be9e"),
                            Description = "A mafia boss tries to balance crime and family.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image1.jpg",
                            ReleaseDate = new DateTime(1999, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Sopranos",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("9edbb15c-b983-450c-b3dd-e18a72627041"),
                            Description = "An in-depth look into crime, bureaucracy and society in Baltimore.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image2.jpg",
                            ReleaseDate = new DateTime(2002, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Wire",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("75e7007f-9c37-4ba5-9a67-015fa83246f4"),
                            Description = "A chemistry teacher becomes a meth kingpin.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image3.jpg",
                            ReleaseDate = new DateTime(2008, 1, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Breaking Bad",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("a7b14e84-b635-4dda-8f79-bc30e55658f9"),
                            Description = "Noble families vie for power in a mythical land.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image4.jpg",
                            ReleaseDate = new DateTime(2011, 4, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Game of Thrones",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("7b7b41bf-ca8e-41ac-af17-77a9ac28de61"),
                            Description = "Kids uncover government secrets and supernatural horrors in 1980s Indiana.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image5.jpg",
                            ReleaseDate = new DateTime(2016, 7, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Stranger Things",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("059d1f15-5e73-4185-8443-732fb93896cf"),
                            Description = "A dramatized history of the British royal family.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image6.jpg",
                            ReleaseDate = new DateTime(2016, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Crown",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("2af5266a-d50f-4e28-80c5-6c093760af08"),
                            Description = "A lone bounty hunter in the Star Wars universe.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image7.jpg",
                            ReleaseDate = new DateTime(2019, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Mandalorian",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("46a0b1b5-29de-4cdd-b5b7-b764354c56c6"),
                            Description = "A mockumentary about office workers in Scranton, PA.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image8.jpg",
                            ReleaseDate = new DateTime(2005, 3, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Office",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("9f71a630-2713-42b2-9cd0-c9b126692dc9"),
                            Description = "Six friends navigating life in New York City.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image9.jpg",
                            ReleaseDate = new DateTime(1994, 9, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Friends",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("70523ed1-d035-4abc-af12-874912c8eacb"),
                            Description = "A show about nothing centered on a quirky group of friends.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image10.jpg",
                            ReleaseDate = new DateTime(1989, 7, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Seinfeld",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("832a5fae-4e9c-42a2-8a8a-be7cb71d72cf"),
                            Description = "The story of criminal lawyer Saul Goodman before Breaking Bad.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image11.jpg",
                            ReleaseDate = new DateTime(2015, 2, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Better Call Saul",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("a8d9245a-3e55-4560-b647-30b53ec7ad49"),
                            Description = "A group takes on corrupt superheroes.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image12.jpg",
                            ReleaseDate = new DateTime(2019, 7, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Boys",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("f4f62b79-258c-458f-8cbc-3e83cc5036f2"),
                            Description = "A hardened survivor escorts a girl across post-apocalyptic America.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image13.jpg",
                            ReleaseDate = new DateTime(2023, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Last of Us",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("92b385db-c0c3-41b1-af1a-58de3d96f93d"),
                            Description = "Desperate contestants play deadly children's games for money.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image14.jpg",
                            ReleaseDate = new DateTime(2021, 9, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Squid Game",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("a02be860-6df6-4a5a-93fb-4366c68f4173"),
                            Description = "A prequel to Game of Thrones about House Targaryen.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image15.jpg",
                            ReleaseDate = new DateTime(2022, 8, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "House of the Dragon",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("4bc3413a-0ba8-41e3-a812-7033d414723a"),
                            Description = "A gangster family in post-WWI Birmingham, England.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image16.jpg",
                            ReleaseDate = new DateTime(2013, 9, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Peaky Blinders",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("beb741d5-4de3-4ca1-bdab-8c09aaa8e2e4"),
                            Description = "A dystopian society where women are forced into servitude.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image17.jpg",
                            ReleaseDate = new DateTime(2017, 4, 26, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Handmaid's Tale",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("31b40b96-c94d-4e8a-962c-542848fe9cf7"),
                            Description = "A theme park where robots develop consciousness.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image18.jpg",
                            ReleaseDate = new DateTime(2016, 10, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Westworld",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("b0fc72dc-d6a7-4102-b076-070463d95cf1"),
                            Description = "A dramatization of the 1986 nuclear disaster.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image19.jpg",
                            ReleaseDate = new DateTime(2019, 5, 6, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Chernobyl",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("9d03bfbc-5cce-4579-94b0-935815eff10f"),
                            Description = "A young chess prodigy rises amid addiction and competition.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image20.jpg",
                            ReleaseDate = new DateTime(2020, 10, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Queen's Gambit",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("d79b763e-4ccf-4af2-8199-751cc76c460d"),
                            Description = "A German sci-fi thriller involving time travel.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image21.jpg",
                            ReleaseDate = new DateTime(2017, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Dark",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("aa38ead2-6eba-4e23-971b-fb8433fd7ebc"),
                            Description = "Anthology series exploring technology's dark side.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image22.jpg",
                            ReleaseDate = new DateTime(2011, 12, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Black Mirror",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("7644bacb-00a1-41d1-9304-54c30643c701"),
                            Description = "Crime stories in the Midwest with dark humor.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image23.jpg",
                            ReleaseDate = new DateTime(2014, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Fargo",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("4c0163de-c05d-48d1-8b89-2fcb944a0d84"),
                            Description = "A family launders drug money in Missouri.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image24.jpg",
                            ReleaseDate = new DateTime(2017, 7, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ozark",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("f6afb32d-5be6-4c40-9666-8845380da7a7"),
                            Description = "A powerful family's battle for control of a media empire.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image25.jpg",
                            ReleaseDate = new DateTime(2018, 6, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Succession",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("0109d92a-1841-41bd-99fa-d61dddecb14d"),
                            Description = "A kind-hearted coach leads a UK soccer team.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image26.jpg",
                            ReleaseDate = new DateTime(2020, 8, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ted Lasso",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("6411c160-6cd6-4234-a9a8-1d6847f9c440"),
                            Description = "The god of mischief causes chaos across timelines.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image27.jpg",
                            ReleaseDate = new DateTime(2021, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Loki",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("812045e3-8584-45ac-8b3e-118566f1e505"),
                            Description = "Superpowered couple trapped in a sitcom reality.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image28.jpg",
                            ReleaseDate = new DateTime(2021, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "WandaVision",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("ae89f7e1-5363-47f7-97d0-28508a32067b"),
                            Description = "A chef returns to run his family’s sandwich shop in Chicago.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image29.jpg",
                            ReleaseDate = new DateTime(2022, 6, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Bear",
                            Type = "TVShow"
                        },
                        new
                        {
                            ContentId = new Guid("bb4b1fb5-1c77-4e31-89d8-664e0ff47885"),
                            Description = "Wednesday Addams navigates high school and murder mysteries.",
                            ImageURL = "https://mreimagestorage.blob.core.windows.net/imagecontainer/tv-image30.jpg",
                            ReleaseDate = new DateTime(2022, 11, 23, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wednesday",
                            Type = "TVShow"
                        });
                });

            modelBuilder.Entity("Domain.Models.ContentCast", b =>
                {
                    b.Property<Guid>("ContentId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CastId")
                        .HasColumnType("TEXT");

                    b.HasKey("ContentId", "CastId");

                    b.HasIndex("CastId");

                    b.ToTable("ContentCasts");
                });

            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ContentId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Rating")
                        .HasColumnType("INTEGER");

                    b.HasKey("ReviewId");

                    b.HasIndex("ContentId");

                    b.ToTable("Reviews", t =>
                        {
                            t.HasCheckConstraint("CK_Review_Rating", "Rating >= 1 AND Rating <= 5");
                        });
                });

            modelBuilder.Entity("Domain.Models.ContentCast", b =>
                {
                    b.HasOne("Domain.Models.Cast", "Cast")
                        .WithMany("ContentCasts")
                        .HasForeignKey("CastId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Domain.Models.Content", "Content")
                        .WithMany("ContentCasts")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cast");

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Domain.Models.Review", b =>
                {
                    b.HasOne("Domain.Models.Content", "Content")
                        .WithMany("Reviews")
                        .HasForeignKey("ContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Content");
                });

            modelBuilder.Entity("Domain.Models.Cast", b =>
                {
                    b.Navigation("ContentCasts");
                });

            modelBuilder.Entity("Domain.Models.Content", b =>
                {
                    b.Navigation("ContentCasts");

                    b.Navigation("Reviews");
                });
#pragma warning restore 612, 618
        }
    }
}
